export const FETCH_USER_REQUEST = "FETCH_USER_REQUEST";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAILED = "FETCH_USER_FAILED";
export const FLAG_ACTION = "FLAG_ACTION";
export const COUNTER_ACTION_PLUS = "COUNTER_ACTION_PLUS";
export const COUNTER_ACTION_MINUS = "COUNTER_ACTION_MINUS";
export const COUNTER_ACTION_DELAY_PLUS = "COUNTER_ACTION_DELAY_PLUS";
